const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const base=path.resolve(__dirname,'..');const out=path.join(base,'qa-artifacts');fs.mkdirSync(out,{recursive:true});
const mime={'.html':'text/html','.js':'application/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
(async()=>{const server=http.createServer((req,res)=>{let f=path.join(base,decodeURIComponent(req.url.split('?')[0]));try{if(fs.statSync(f).isDirectory())f=path.join(f,'index.html');res.setHeader('Content-Type',mime[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f))}catch{res.statusCode=404;res.end('Not found')}});await new Promise(r=>server.listen(8765,'127.0.0.1',r));
const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox']}: {})});const results=[];
const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'block',acceptDownloads:true});
await context.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:8765')?r.continue():r.abort());
const page=await context.newPage();await page.clock.setFixedTime(new Date('2026-09-18T18:00:00Z'));let errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=async route=>{errors=[];await page.goto('http://127.0.0.1:8765/'+route);await page.waitForTimeout(900);};
async function test(name,fn){try{await fn();results.push({name,ok:true});console.log('PASS',name)}catch(e){results.push({name,ok:false,error:e.message});console.log('FAIL',name,e.message.slice(0,300));}}
await test('Inicio: filtro de módulos y consulta de reservas',async()=>{await go('');await page.fill('#moduleSearch','riego');assert.equal(await page.locator('.mod-card:visible').count(),1);await page.fill('#moduleSearch','');await page.click('#loadPriorities');await page.waitForFunction(()=>document.querySelector('#homePriorities b'));assert.equal(await page.locator('#homePriorities b').first().innerText(),'3');await page.screenshot({path:out+'/inicio-pc.png'});assert.deepEqual(errors,[])});
await test('Navegación: módulo integrado y selector común',async()=>{await page.locator('.mod-card').filter({hasText:'Insumos Entregados'}).click();await page.frameLocator('#mFrame').locator('#chartUnit').waitFor();await page.selectOption('#suiteModuleSelect','tch');await page.frameLocator('#mFrame').locator('[data-route="biometry"]').first().waitFor();await page.click('#mBack');await page.locator('#moduleSearch').waitFor({state:'visible'});});
await test('Insumos: conservación de indicadores y unidades separadas',async()=>{await go('modules/insumos/');await page.waitForFunction(()=>typeof STATE!=='undefined'&&STATE.events.length>0);const k=await page.evaluate(()=>{const k=computeKPIs();return{executed:k.eje.length,reserved:k.res.length,physical:k.supFisica,events:k.ins.length}});assert.equal(k.executed,218);assert.equal(k.reserved,3);assert.equal(k.events,221);assert(Math.abs(k.physical-759.9)<.1);assert.equal(await page.locator('#chartUnit').inputValue(),'KG');await page.selectOption('#chartUnit','LT');assert.equal(await page.locator('.casur-unit-chart').getAttribute('data-chart-unit'),'LT');const vals=await page.locator('.casur-unit-chart .casur-bar-value').allTextContents();assert(vals.every(v=>v.endsWith('LT')));await page.screenshot({path:out+'/insumos-pc.png'});assert.deepEqual(errors,[])});
await test('Insumos: selección múltiple, ninguno, todos y paginación',async()=>{await page.click('[data-nav="explora"]');await page.click('[data-multi-field="estado"] > summary');await page.click('[data-multi-none="estado"]');assert.equal(await page.evaluate(()=>filterExplorerEvents().length),0);await page.check('[data-multi-option="estado"][value="RESERVADA"]');assert.equal(await page.evaluate(()=>filterExplorerEvents().length),3);await page.click('[data-multi-all="estado"]');assert.equal(await page.evaluate(()=>filterExplorerEvents().length),221);await page.click('[data-multi-field="estado"] > summary');assert.equal(await page.locator('.ev-row').count(),100);await page.click('[data-explorer-page="1"]');assert.equal(await page.locator('.ev-row').count(),100);await page.click('[data-explorer-page="2"]');assert.equal(await page.locator('.ev-row').count(),21);assert.deepEqual(errors,[])});
await test('Insumos: exportación real de selección y contexto',async()=>{await page.click('[data-multi-field="estado"] > summary');await page.click('[data-multi-none="estado"]');await page.check('[data-multi-option="estado"][value="RESERVADA"]');await page.click('[data-multi-field="estado"] > summary');const promise=page.waitForEvent('download');await page.click('[data-export="explora"]');const d=await promise;await d.saveAs(out+'/reservas.xlsx');const wb=await page.evaluate(()=>{let result;const original=XLSX.writeFile;XLSX.writeFile=w=>result=w;try{exportXLSX('explora')}finally{XLSX.writeFile=original}return{rows:XLSX.utils.sheet_to_json(result.Sheets['Eventos filtrados']),context:XLSX.utils.sheet_to_json(result.Sheets.Contexto)}});assert.equal(wb.rows.length,3);assert(wb.rows.every(r=>r.Estado==='RESERVADA'));assert(wb.context.some(r=>r.Campo==='Corte de datos'&&r.Valor==='2026-09-06'));});
await test('Insumos: exportación respeta búsqueda de producto',async()=>{await page.click('[data-nav="insumos"]');await page.fill('[data-f="insumos.search"]','ENVOKE');await page.waitForTimeout(400);const data=await page.evaluate(()=>{let w;const old=XLSX.writeFile;XLSX.writeFile=x=>w=x;try{exportXLSX('insumos')}finally{XLSX.writeFile=old}return{rows:XLSX.utils.sheet_to_json(w.Sheets.Insumos),details:XLSX.utils.sheet_to_json(w.Sheets.Detalle)}});assert.equal(data.rows.length,1);assert(data.details.every(r=>r.Producto.includes('ENVOKE')));});
await test('Producción: barras cero, etiquetas y escala de TCH',async()=>{await go('modules/produccion/');const html=await page.evaluate(()=>hbar([{key:'Cero',area:0},{key:'Grande',area:100}], 'area'));assert(html.includes('width:0%'));assert(!html.includes('class="hfill bad"'));assert(html.includes('ha'));const trend=await page.evaluate(()=>lineChart([{label:'24/25',tch:60},{label:'25/26',tch:70}]));assert(trend.includes('TCH (t/ha)'));assert(trend.includes('promedio simple'));await page.screenshot({path:out+'/produccion-pc.png'});assert.deepEqual(errors,[])});
await test('TCH: sin evaluaciones no muestra producción cero',async()=>{await go('modules/tch/');assert((await page.locator('body').innerText()).includes('Sin biometrías guardadas'));await page.screenshot({path:out+'/tch-pc.png'});assert.deepEqual(errors,[])});
await test('Riego: carga directa y conservación del resumen',async()=>{await go('modules/riego/');await page.waitForFunction(()=>document.body.innerText.includes('441.2'));const text=await page.locator('body').innerText();for(const str of ['441.2','153.8','146.4','71 días','35 días'])assert(text.includes(str),str);await page.screenshot({path:out+'/riego-pc.png'});assert.deepEqual(errors,[])});
await test('Labores: datos base y navegación de detalle',async()=>{await go('modules/labores/');await page.waitForFunction(()=>document.body.innerText.includes('3,376.5'));const text=await page.locator('body').innerText();assert(text.includes('219,324.0'));await page.screenshot({path:out+'/labores-pc.png'});await page.getByRole('button',{name:'Productores',exact:true}).click();assert.deepEqual(errors,[])});
await test('Riego: exportación de imagen y Excel',async()=>{await go('modules/riego/');await page.waitForFunction(()=>document.body.innerText.includes('441.2'));const image=page.waitForEvent('download',{timeout:45000});await page.getByRole('button',{name:'Exportar imagen',exact:true}).click();const png=await image;await png.saveAs(out+'/riego-export.png');assert(fs.statSync(out+'/riego-export.png').size>5000);const excel=page.waitForEvent('download');await page.getByRole('button',{name:'Reporte Excel',exact:true}).click();const x=await excel;await x.saveAs(out+'/riego-export.xlsx');assert(fs.statSync(out+'/riego-export.xlsx').size>1000);});
await test('Tabla de Insumos: columnas visibles y restauración',async()=>{await go('modules/insumos/');await page.click('[data-nav="explora"]');await page.locator('.casur-table-tools summary').first().waitFor();await page.locator('.casur-table-tools summary').first().click();const check=page.locator('.casur-column-options input').nth(3);await check.uncheck();assert(await page.locator('th').nth(3).evaluate(e=>getComputedStyle(e).display==='none'));await page.getByRole('button',{name:'Mostrar todas',exact:true}).first().click();assert(await page.locator('th').nth(3).evaluate(e=>getComputedStyle(e).display!=='none'));});
const inspection=[];
for(const [name,route] of [['inicio',''],['produccion','modules/produccion/'],['tch','modules/tch/'],['riego','modules/riego/'],['insumos','modules/insumos/'],['labores','modules/labores/'],['inventario','modules/inventario/']]){
 await test('Móvil 390px: '+name,async()=>{await page.setViewportSize({width:390,height:844});await go(route);await page.waitForTimeout(name==='labores'?1500:200);const dims=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));inspection.push({name,dims,errors});assert(dims.scroll<=dims.w+1,JSON.stringify(dims));assert.deepEqual(errors,[]);await page.screenshot({path:out+'/'+name+'-movil.png'});});
}
await page.setViewportSize({width:1440,height:1000});
for(const route of ['modules/produccion/','modules/riego/','modules/labores/']){await go(route);inspection.push({route,labels:await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.children.length===0&&['EM-CT','Módulo técnico','Ver desglose','146.0 ha · 21 suertes'].includes(e.textContent.trim())).map(e=>({text:e.textContent,tag:e.tagName,cls:e.className,parent:e.parentElement.className,color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor})))})}
fs.writeFileSync(out+'/results.json',JSON.stringify({results,inspection},null,2));await browser.close();server.close();if(results.some(r=>!r.ok))process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
